trigger:
- main

pool: shagent

variables:
  AZURE_STORAGE_ACCOUNT: 'sachirag'
  AZURE_STORAGE_CONTAINER: 'azure-test-space'
  DOWNLOAD_DIR: '$(Build.ArtifactStagingDirectory)/devopsdir'
  FILE_NAME: 'new_doc.txt.txt'

stages:
  - stage: List_Publish_Blob_Files
    displayName: List Publish Blob Container file
    jobs:
      - job: download
        steps:
        - task: AzureCLI@2
          displayName: Downloading and List Blob files
          inputs:
            azureSubscription: 'azure_storage'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Logging in to Azure using the service principal..."
              
              echo "Listing blobs and finding the latest one..."
              latest_blob=$(az storage blob list \
                --container-name $AZURE_STORAGE_CONTAINER \
                --account-name $AZURE_STORAGE_ACCOUNT \
                --query '[].{name:name, lastModified:properties.lastModified}' --connection-string "$(AZURE_STORAGE_CONNECTION_STRING)"\
                --output tsv | sort -r -k2 | head -n1 | cut -f1)
              
              if [ -z "$latest_blob" ]; then
                echo "No blobs found in the container with the specified prefix."
                exit 1
              fi
              
              echo "Latest blob: $latest_blob"
              
              echo "Creating download directory..."
              mkdir -p $DOWNLOAD_DIR
              
              echo "Downloading the latest blob..."
              az storage blob download \
                --container-name $AZURE_STORAGE_CONTAINER \
                --account-name $AZURE_STORAGE_ACCOUNT \
                --name "$latest_blob" \
                --file "$DOWNLOAD_DIR/$FILE_NAME"
              
              echo "Setting pipeline variable for the downloaded file name..."
              echo "##vso[task.setvariable variable=downloadfilename]$FILE_NAME"
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(DOWNLOAD_DIR)'
            ArtifactName: 'downloaded-blob'
            publishLocation: 'Container'
          displayName: 'Publish Blob Artifact'

  - stage: Download_Blob
    dependsOn: List_Publish_Blob_Files
    condition: succeeded()
    jobs:
      - job: download_blob
        steps:
          - download: current
            artifact: 'downloaded-blob'
            displayName: Downloading Blob File for Py
